---
# file: roles/pacemaker/tasks/controller_vip.yml
#
- name: Add resource controller-vip
  pcs_resource:
    command: create
    resource_id: controller-vip
    res_class: ocf
    res_provider: hearbeat
    res_type: IPaddr2
    attributes:
      - options:
          ip: "{{ controller_vip }}"
          cidr_netmask: "{{ controller_vip_cidr }}"
    operations:
      - action: start
        options:
          interval: 0s
          timeout: 20s
      - action: stop
        options:
          interval: 0s
          timeout: 20s
      - action: monitor
        options:
          interval: 10s
          timeout: 20s
  run_once: true
  tags:
    - pacemaker
    - pacemaker-controller-vip

