---
# file: roles/pacemaker/config_nodes/hosts.yml
#
- name : update hostname
  hostname : name={{ inventory_hostname }}
- name : update /etc/hosts
  lineinfile : 
    dest=/etc/hosts line="{{ hostvars.get(item).ansible_default_ipv4.address }} {{ item }}"
  with_items: "{{ play_hosts }}"

#- name: Configure the host node /etc/hosts
#  template: src=etc/hosts  dest=/etc/hosts
