---
# file: roles/pacemaker/tasks/destroy.yml
- include: stop.yml

- name: Destroying Pacemaker cluster
  pcs_cluster:
    command=destroy
  run_once: true

- name: Purging tokens and configuration related to pcsd
  file:
    path=/var/lib/pcsd/{{ item }}
    state=absent
  with_fileglob:
    - pcsd.cookiesecret
    - pcsd.crt
    - pcsd.key
    - tokens
    - pcs_users.conf

