---
# file: roles/pacemaker/tasks/destroy.yml
- name: Stopping Pacemaker cluster
  pcs_cluster:
    command=stop
  run_once: true
  tags:
    - pacemaker
    - pacemaker-destroy

- name: Destroying Pacemaker cluster
  pcs_cluster:
    command=destroy
  run_once: true
  tags:
    - pacemaker
    - pacemaker-destroy

- name: Purging tokens and configuration related to pcsd
  file:
    path=/var/lib/pcsd/{{ item }}
    state=absent
  with_fileglob:
    - pcsd.cookiesecret
    - pcsd.crt
    - pcsd.key
    - tokens
    - pcs_users.conf
  tags:
    - pacemaker
    - pacemaker-destroy
