---
# file: roles/pacemaker/tasks/main.yml
# tasks file for pacemaker

- name: OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - pacemaker
    - pacemaker-setup
    - pacemaker-destroy
    - firewall

# Stopping Pacemaker cluster
- include: destroy.yml
  when: pacemaker_destroy_cluster is defined and pacemaker_destroy_cluster == true
  tags:
    - pacemaker
    - pacemaker-destroy

# Config Pacemaker/pcsd firewalld rules
- include: firewall.yml
  when: pacemaker_firewalld is defined and pacemaker_firewalld == true
  tags:
    - firewall

# RedHat(setup) specific tasks
- include: setup_redhat.yml
  when: "ansible_os_family == 'RedHat'"
  tags:
    - pacemaker
    - pacemaker-setup

# Common pcsd service tasks
- include: pcsd_service.yml
  tags:
    - pacemaker

# Set hacluster user, haclient group
- include: user.yml
  tags:
    - pacemaker
    - pacemaker-user
    - pacemaker-group

# Authenticating to pcsd daemon
- include: auth.yml
  tags:
    - pacemaker
    - pacemaker-auth

# Common configuration tasks
- include: config_cluster.yml
  tags:
    - pacemaker
    - pacemaker_config_cluster

# Starting Pacemaker/Corosync cluster everywhere
- include: start.yml
  tags:
    - pacemaker
    - pacemaker-start

