---
# file: roles/pacemaker/tasks/service.yml
#
#- name: Ensure pacemaker service is started/stopped
#  service:
#    name: '{{ pacemaker_service }}'
#    state: '{{ pacemaker_service_state }}'
#    enabled: '{{ pacemaker_service_enabled }}'
#  tags:
#    - pacemaker
#    - service

- name: Ensure pcsd service is started/stopped
  service:
    name: '{{ pcsd_service }}'
    state: '{{ pcsd_service_state }}'
    enabled: '{{ pcsd_service_enabled }}'

