---
# file: roles/pacemaker/tasks/setup_redhat.yml
#
- name: install pacemaker
  yum:
    pkg: '{{ item }}'
    state: '{{ pacemaker_package_state }}'
  tags:
    - pacemaker
    - setup
  with_items: pacemaker_packages

